version: "3.2"
services:
  storybook:
    container_name: frontmania_storybook
    image: node:8-alpine
    working_dir: '/app'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '19009:9009'
    command: >
      sh -c "yarn install && yarn storybook -h 0.0.0.0 --ci"
  
  test:
    container_name: frontmania_test
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - "storybook:storybook"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src/__tests__/snapshots/__image_snapshots__:/app/src/__tests__/snapshots/__image_snapshots__
    depends_on:
      - storybook
    command: sh -c "yarn docker:test"