# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run:
          name: storing local IP address
          command: mkdir storybook-static && yarn build:storybook

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: "pwd"
      - run: "ls -lah"
      - run: "ls -lah storybook-static" 
      - run: "cat $(pwd)/storybook-static/index.html" 
      - run: "cat file://$(pwd)/storybook-static/index.html" 

      # run tests!
      - run: "CI=true STORYBOOK_URL=file://$(pwd)/storybook-static yarn test"